.TH "TinyLib/Graphics Directory Reference" 3 "Version 0.1.0" "TinyLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TinyLib/Graphics Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDrawable\&.cpp\fP"
.br
.ti -1c
.RI "file \fBDrawable\&.h\fP"
.br
.ti -1c
.RI "file \fBGraphicsCategory\&.h\fP"
.br
.ti -1c
.RI "file \fBRectangle\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRectangle\&.h\fP"
.br
.ti -1c
.RI "file \fBText\&.cpp\fP"
.br
.ti -1c
.RI "file \fBText\&.h\fP"
.br
.ti -1c
.RI "file \fBWindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBWindow\&.h\fP"
.br
.in -1c
