.TH "TinyLib/System Directory Reference" 3 "Version 0.1.0" "TinyLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TinyLib/System Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBFile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBFile\&.h\fP"
.br
.ti -1c
.RI "file \fBKey\&.cpp\fP"
.br
.ti -1c
.RI "file \fBKey\&.h\fP"
.br
.ti -1c
.RI "file \fBMouse\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMouse\&.h\fP"
.br
.ti -1c
.RI "file \fBSystemCategory\&.h\fP"
.br
.in -1c
