.TH "TinyLib/Console Directory Reference" 3 "Version 0.1.0" "TinyLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TinyLib/Console Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBConsole\&.cpp\fP"
.br
.ti -1c
.RI "file \fBConsole\&.h\fP"
.br
.ti -1c
.RI "file \fBConsoleCategory\&.h\fP"
.br
.in -1c
