.TH "TinyLib/Graphics/GraphicsCategory.h" 3 "Version 0.1.0" "TinyLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TinyLib/Graphics/GraphicsCategory.h
.SH SYNOPSIS
.br
.PP
\fR#include 'Window\&.h'\fP
.br
\fR#include 'Drawable\&.h'\fP
.br
\fR#include 'Rectangle\&.h'\fP
.br
\fR#include 'Graphics\&.h'\fP
.br
\fR#include 'GDI\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for TinyLib from the source code\&.
