.TH "TinyLib/System/Key.h" 3 "Version 0.1.0" "TinyLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TinyLib/System/Key.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./Base/Win/WinAPI\&.h'\fP
.br
\fR#include '\&.\&./Base/Types\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtl::Key\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TinyLib from the source code\&.
