.TH "TinyLib/Graphics/Text.cpp" 3 "Version 0.1.0" "TinyLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TinyLib/Graphics/Text.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'Text\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TinyLib from the source code\&.
