.TH "tl::Color" 3 "Version 0.1.0" "TinyLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tl::Color
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Types\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColor\fP (\fBu8\fP red=0, \fBu8\fP green=0, \fBu8\fP blue=0, \fBu8\fP alpha=255)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBr\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBg\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBb\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBa\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB106\fP of file \fBTypes\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tl::Color::Color (\fBu8\fP red = \fR0\fP, \fBu8\fP green = \fR0\fP, \fBu8\fP blue = \fR0\fP, \fBu8\fP alpha = \fR255\fP)\fR [inline]\fP"

.PP
Definition at line \fB110\fP of file \fBTypes\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBu8\fP tl::Color::a"

.PP
Definition at line \fB108\fP of file \fBTypes\&.h\fP\&.
.SS "\fBu8\fP tl::Color::b"

.PP
Definition at line \fB108\fP of file \fBTypes\&.h\fP\&.
.SS "\fBu8\fP tl::Color::g"

.PP
Definition at line \fB108\fP of file \fBTypes\&.h\fP\&.
.SS "\fBu8\fP tl::Color::r"

.PP
Definition at line \fB108\fP of file \fBTypes\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TinyLib from the source code\&.
