.TH "tl::Key" 3 "Version 0.1.0" "TinyLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tl::Key
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Key\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBSpace\fP = VK_SPACE, \fBA\fP = 0x41, \fBB\fP = 0x42, \fBC\fP = 0x43, \fBD\fP = 0x44, \fBE\fP = 0x45, \fBF\fP = 0x46, \fBG\fP = 0x47, \fBH\fP = 0x48, \fBI\fP = 0x49, \fBJ\fP = 0x4A, \fBK\fP = 0x4B, \fBL\fP = 0x4C, \fBM\fP = 0x4D, \fBN\fP = 0x4E, \fBO\fP = 0x4F, \fBP\fP = 0x50, \fBQ\fP = 0x51, \fBR\fP = 0x52, \fBS\fP = 0x53, \fBT\fP = 0x54, \fBU\fP = 0x55, \fBV\fP = 0x56, \fBW\fP = 0x57, \fBX\fP = 0x58, \fBY\fP = 0x59, \fBZ\fP = 0x5A, \fBNum0\fP = 0x30, \fBNum1\fP = 0x31, \fBNum2\fP = 0x32, \fBNum3\fP = 0x33, \fBNum4\fP = 0x34, \fBLShift\fP = VK_LSHIFT, \fBRShift\fP = VK_RSHIFT, \fBLControl\fP = VK_LCONTROL, \fBRControl\fP = VK_RCONTROL, \fBLAlt\fP = VK_LMENU, \fBRAlt\fP = VK_RMENU, \fBUp\fP = VK_UP, \fBDown\fP = VK_DOWN, \fBLeft\fP = VK_LEFT, \fBRight\fP = VK_RIGHT }"
.br
.RI "Readable version for every standard keyboard key\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBbit\fP \fBisHeld\fP (\fBu8\fP key)"
.br
.RI "Check if this key is currently down\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBKey\&.h\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
Readable version for every standard keyboard key\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BISpace \fP
.TP
\f(BIA \fP
.TP
\f(BIB \fP
.TP
\f(BIC \fP
.TP
\f(BID \fP
.TP
\f(BIE \fP
.TP
\f(BIF \fP
.TP
\f(BIG \fP
.TP
\f(BIH \fP
.TP
\f(BII \fP
.TP
\f(BIJ \fP
.TP
\f(BIK \fP
.TP
\f(BIL \fP
.TP
\f(BIM \fP
.TP
\f(BIN \fP
.TP
\f(BIO \fP
.TP
\f(BIP \fP
.TP
\f(BIQ \fP
.TP
\f(BIR \fP
.TP
\f(BIS \fP
.TP
\f(BIT \fP
.TP
\f(BIU \fP
.TP
\f(BIV \fP
.TP
\f(BIW \fP
.TP
\f(BIX \fP
.TP
\f(BIY \fP
.TP
\f(BIZ \fP
.TP
\f(BINum0 \fP
.TP
\f(BINum1 \fP
.TP
\f(BINum2 \fP
.TP
\f(BINum3 \fP
.TP
\f(BINum4 \fP
.TP
\f(BILShift \fP
.TP
\f(BIRShift \fP
.TP
\f(BILControl \fP
.TP
\f(BIRControl \fP
.TP
\f(BILAlt \fP
.TP
\f(BIRAlt \fP
.TP
\f(BIUp \fP
.TP
\f(BIDown \fP
.TP
\f(BILeft \fP
.TP
\f(BIRight \fP
.PP
Definition at line \fB16\fP of file \fBKey\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBbit\fP tl::Key::isHeld (\fBu8\fP key)\fR [static]\fP"

.PP
Check if this key is currently down\&. 
.PP
\fBParameters\fP
.RS 4
\fIkey\fP Which key to check, use enum \fBtl::Key\fP\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if this key is currently down\&. 
.RE
.PP

.PP
Definition at line \fB9\fP of file \fBKey\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TinyLib from the source code\&.
