.TH "tl::Time" 3 "Version 0.1.0" "TinyLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tl::Time
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Time\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTime\fP ()"
.br
.RI "\fBTime\fP value gets set right away upon creation\&. "
.ti -1c
.RI "\fBTime\fP (\fBu64\fP timeValue)"
.br
.RI "Probably avoid this for now lol\&. - I plan to change it later\&. "
.ti -1c
.RI "\fB~Time\fP ()"
.br
.RI "Nothing to clean up here for now\&. "
.ti -1c
.RI "\fBu64\fP \fBgetTime\fP ()"
.br
.RI "Get the current time data from this object\&. "
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.RI "Update the time data to what it should be right now\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBu64\fP \fBcurrentTime\fP ()"
.br
.RI "Static way to get a current time value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBTime\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tl::Time::Time ()"

.PP
\fBTime\fP value gets set right away upon creation\&. 
.PP
Definition at line \fB7\fP of file \fBTime\&.cpp\fP\&.
.SS "tl::Time::Time (\fBu64\fP timeValue)"

.PP
Probably avoid this for now lol\&. - I plan to change it later\&. 
.PP
\fBParameters\fP
.RS 4
\fItimeValue\fP What number you want the internal time data as\&. 
.RE
.PP

.PP
Definition at line \fB15\fP of file \fBTime\&.cpp\fP\&.
.SS "tl::Time::~Time ()"

.PP
Nothing to clean up here for now\&. 
.PP
Definition at line \fB22\fP of file \fBTime\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBu64\fP tl::Time::currentTime ()\fR [static]\fP"

.PP
Static way to get a current time value\&. 
.PP
\fBReturns\fP
.RS 4
Current time value\&. 
.RE
.PP

.PP
Definition at line \fB45\fP of file \fBTime\&.cpp\fP\&.
.SS "\fBu64\fP tl::Time::getTime ()"

.PP
Get the current time data from this object\&. 
.PP
\fBReturns\fP
.RS 4
\fBTime\fP data\&. 
.RE
.PP

.PP
Definition at line \fB30\fP of file \fBTime\&.cpp\fP\&.
.SS "void tl::Time::update ()"

.PP
Update the time data to what it should be right now\&. 
.PP
Definition at line \fB37\fP of file \fBTime\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TinyLib from the source code\&.
