.TH "tl::Text" 3 "Version 0.1.0" "TinyLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tl::Text
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Text\&.h>\fP
.PP
Inherits \fBtl::Drawable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBText\fP (const \fBascii\fP *=nullptr, \fBu32\fP=12, \fBVec2i\fP={ 0, 0 })"
.br
.RI "Create a new text that can be drawn to screen\&. "
.ti -1c
.RI "\fB~Text\fP ()"
.br
.RI "Clean up string data\&. "
.ti -1c
.RI "void \fBsetString\fP (const \fBascii\fP *)"
.br
.RI "Set the string data\&. "
.ti -1c
.RI "\fBascii\fP * \fBgetString\fP () const"
.br
.RI "Get the string data from this text\&. "
.ti -1c
.RI "void \fBsetFontSize\fP (\fBs32\fP)"
.br
.RI "Set the font size for this text\&. "
.in -1c

Public Member Functions inherited from \fBtl::Drawable\fP
.in +1c
.ti -1c
.RI "\fBDrawable\fP (\fBVec4i\fP bounds={0, 0, 0, 0})"
.br
.RI "Creates a new drawable object with it's position and size\&. "
.ti -1c
.RI "\fB~Drawable\fP ()"
.br
.RI "Nothing to clean up for now\&. "
.ti -1c
.RI "void \fBsetPosition\fP (\fBVec2i\fP)"
.br
.RI "Set position of this drawable object\&. "
.ti -1c
.RI "void \fBsetSize\fP (\fBVec2i\fP)"
.br
.RI "Set size of this drawable object\&. "
.ti -1c
.RI "\fBVec2i\fP \fBgetPosition\fP () const"
.br
.RI "Get the current position of this drawable object\&. "
.ti -1c
.RI "\fBVec2i\fP \fBgetSize\fP () const"
.br
.RI "Get the current size of this drawable object\&. "
.ti -1c
.RI "\fBColor\fP \fBgetColor\fP () const"
.br
.RI "Get the current color of this drawable object\&. "
.ti -1c
.RI "void \fBmove\fP (\fBVec2i\fP)"
.br
.RI "Move this drawable object from current position\&. "
.ti -1c
.RI "void \fBsetColor\fP (\fBColor\fP)"
.br
.RI "Set the color of this drawable object\&. "
.ti -1c
.RI "\fBbit\fP \fBintersects\fP (\fBDrawable\fP &) const"
.br
.RI "Check if this drawable is intersecting with another\&. "
.ti -1c
.RI "\fBbit\fP \fBintersects\fP (\fBWindow\fP &) const"
.br
.RI "Check if this drawable is inside the window\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBtl::Drawable\fP
.in +1c
.ti -1c
.RI "\fBs32\fP \fBposX\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBposY\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBsizeX\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBsizeY\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBr\fP = 0"
.br
.ti -1c
.RI "\fBu8\fP \fBg\fP = 0"
.br
.ti -1c
.RI "\fBu8\fP \fBb\fP = 0"
.br
.ti -1c
.RI "\fBu8\fP \fBa\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBText\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tl::Text::Text (const \fBascii\fP * str = \fRnullptr\fP, \fBu32\fP fontSize = \fR12\fP, \fBVec2i\fP pos = \fR{ 0, 0 }\fP)"

.PP
Create a new text that can be drawn to screen\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP What the text displays\&. 
.br
\fIfontSize\fP How big text is\&. 
.br
\fIpos\fP Where text is\&.
.RE
.PP
The defaults for each parameter, no string data, fonst size 12, position (0, 0)\&. 
.PP
Definition at line \fB13\fP of file \fBText\&.cpp\fP\&.
.SS "tl::Text::~Text ()"

.PP
Clean up string data\&. 
.PP
Definition at line \fB22\fP of file \fBText\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBascii\fP * tl::Text::getString () const"

.PP
Get the string data from this text\&. 
.PP
\fBReturns\fP
.RS 4
Internal string\&. 
.RE
.PP

.PP
Definition at line \fB51\fP of file \fBText\&.cpp\fP\&.
.SS "void tl::Text::setFontSize (\fBs32\fP size)"

.PP
Set the font size for this text\&. 
.PP
\fBParameters\fP
.RS 4
\fIsize\fP New font size\&.
.RE
.PP
I might change how font size scales later on, it doesn't seem to be accurate based on pixels when using GDI/DirectX\&. 
.PP
Definition at line \fB62\fP of file \fBText\&.cpp\fP\&.
.SS "void tl::Text::setString (const \fBascii\fP * str)"

.PP
Set the string data\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP New string for text\&. 
.RE
.PP

.PP
Definition at line \fB30\fP of file \fBText\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TinyLib from the source code\&.
