.TH "tl::Vec2i" 3 "Version 0.1.0" "TinyLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tl::Vec2i
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Types\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVec2i\fP (\fBs32\fP xValue=0, \fBs32\fP yValue=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBs32\fP \fBx\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB64\fP of file \fBTypes\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tl::Vec2i::Vec2i (\fBs32\fP xValue = \fR0\fP, \fBs32\fP yValue = \fR0\fP)\fR [inline]\fP"

.PP
Definition at line \fB68\fP of file \fBTypes\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBs32\fP tl::Vec2i::x"

.PP
Definition at line \fB66\fP of file \fBTypes\&.h\fP\&.
.SS "\fBs32\fP tl::Vec2i::y"

.PP
Definition at line \fB66\fP of file \fBTypes\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TinyLib from the source code\&.
