.TH "tl::Vec3i" 3 "Version 0.1.0" "TinyLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tl::Vec3i
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Types\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVec3i\fP (\fBs32\fP xValue=0, \fBs32\fP yValue=0, \fBs32\fP zValue=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBs32\fP \fBx\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBy\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB77\fP of file \fBTypes\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tl::Vec3i::Vec3i (\fBs32\fP xValue = \fR0\fP, \fBs32\fP yValue = \fR0\fP, \fBs32\fP zValue = \fR0\fP)\fR [inline]\fP"

.PP
Definition at line \fB81\fP of file \fBTypes\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBs32\fP tl::Vec3i::x"

.PP
Definition at line \fB79\fP of file \fBTypes\&.h\fP\&.
.SS "\fBs32\fP tl::Vec3i::y"

.PP
Definition at line \fB79\fP of file \fBTypes\&.h\fP\&.
.SS "\fBs32\fP tl::Vec3i::z"

.PP
Definition at line \fB79\fP of file \fBTypes\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TinyLib from the source code\&.
