.TH "tl::Vec4i" 3 "Version 0.1.0" "TinyLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tl::Vec4i
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Types\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVec4i\fP (\fBs32\fP newWidth=0, \fBs32\fP newHeight=0, \fBs32\fP newLeft=0, \fBs32\fP newTop=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBs32\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBheight\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBleft\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBtop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB91\fP of file \fBTypes\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tl::Vec4i::Vec4i (\fBs32\fP newWidth = \fR0\fP, \fBs32\fP newHeight = \fR0\fP, \fBs32\fP newLeft = \fR0\fP, \fBs32\fP newTop = \fR0\fP)\fR [inline]\fP"

.PP
Definition at line \fB95\fP of file \fBTypes\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBs32\fP tl::Vec4i::height"

.PP
Definition at line \fB93\fP of file \fBTypes\&.h\fP\&.
.SS "\fBs32\fP tl::Vec4i::left"

.PP
Definition at line \fB93\fP of file \fBTypes\&.h\fP\&.
.SS "\fBs32\fP tl::Vec4i::top"

.PP
Definition at line \fB93\fP of file \fBTypes\&.h\fP\&.
.SS "\fBs32\fP tl::Vec4i::width"

.PP
Definition at line \fB93\fP of file \fBTypes\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TinyLib from the source code\&.
