.TH "TinyLib/Base/Types.h" 3 "Version 0.1.0" "TinyLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TinyLib/Base/Types.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtl::Vec2i\fP"
.br
.ti -1c
.RI "struct \fBtl::Vec3i\fP"
.br
.ti -1c
.RI "struct \fBtl::Vec4i\fP"
.br
.ti -1c
.RI "struct \fBtl::Color\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtl\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBtl::s8\fP = signed char"
.br
.ti -1c
.RI "using \fBtl::s16\fP = signed short"
.br
.ti -1c
.RI "using \fBtl::s32\fP = signed int"
.br
.ti -1c
.RI "using \fBtl::s64\fP = signed long long"
.br
.ti -1c
.RI "using \fBtl::u8\fP = unsigned char"
.br
.ti -1c
.RI "using \fBtl::u16\fP = unsigned short"
.br
.ti -1c
.RI "using \fBtl::u32\fP = unsigned int"
.br
.ti -1c
.RI "using \fBtl::u64\fP = unsigned long long"
.br
.ti -1c
.RI "using \fBtl::f32\fP = float"
.br
.ti -1c
.RI "using \fBtl::f64\fP = double"
.br
.ti -1c
.RI "using \fBtl::ascii\fP = char"
.br
.ti -1c
.RI "using \fBtl::unicode\fP = wchar_t"
.br
.ti -1c
.RI "using \fBtl::bit\fP = bool"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TinyLib from the source code\&.
