.TH "TinyLib/Base/Win/WinAPI.h" 3 "Version 0.1.0" "TinyLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TinyLib/Base/Win/WinAPI.h
.SH SYNOPSIS
.br
.PP
\fR#include <Windows\&.h>\fP
.br
\fR#include <d3d11\&.h>\fP
.br
\fR#include <dxgi1_2\&.h>\fP
.br
\fR#include <d3dcompiler\&.h>\fP
.br
\fR#include <DirectXMath\&.h>\fP
.br
\fR#include <wrl/client\&.h>\fP
.br
\fR#include <dwrite\&.h>\fP
.br
\fR#include <d2d1\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_WIN32_WINNT\fP   0x0601"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _WIN32_WINNT   0x0601"

.PP
Definition at line \fB5\fP of file \fBWinAPI\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TinyLib from the source code\&.
