.TH "TinyLib/Graphics/Window.h" 3 "Version 0.1.0" "TinyLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TinyLib/Graphics/Window.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./Base/Win/WinAPI\&.h'\fP
.br
\fR#include 'Drawable\&.h'\fP
.br
\fR#include 'Rectangle\&.h'\fP
.br
\fR#include 'Graphics\&.h'\fP
.br
\fR#include 'GDI\&.h'\fP
.br
\fR#include 'Text\&.h'\fP
.br
\fR#include '\&.\&./Base/BaseCategory\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtl::Window\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtl\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBtl::Event\fP { \fBtl::Closed\fP = 0b1, \fBtl::Moved\fP = 0b10, \fBtl::Resized\fP = 0b100 }"
.br
.ti -1c
.RI "enum \fBtl::Style\fP { \fBtl::Border\fP = WS_BORDER, \fBtl::Title\fP = WS_CAPTION, \fBtl::Background\fP = WS_MINIMIZE, \fBtl::Fullscreen\fP = WS_MAXIMIZE, \fBtl::Minimize\fP = WS_MINIMIZEBOX, \fBtl::Maximize\fP = WS_MAXIMIZEBOX, \fBtl::Resize\fP = WS_SIZEBOX, \fBtl::Default\fP = WS_OVERLAPPEDWINDOW }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TinyLib from the source code\&.
